# Generated by Django 4.2.27 on 2025-12-13 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Аталышы"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon class", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категориялар",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Аталышы")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(verbose_name="Сүрөттөмө")),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("onetime", "Бир жолку"),
                            ("daily", "Күнүмдүк"),
                            ("parttime", "Подработка"),
                            ("fulltime", "Толук жумуш"),
                        ],
                        default="onetime",
                        max_length=10,
                        verbose_name="Түрү",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Баа сомдо көрсөтүлөт",
                        max_digits=10,
                        verbose_name="Баасы (сом)",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Жайгашкан жер"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Байланыш телефону"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активдүү"),
                            ("completed", "Аткарылды"),
                            ("cancelled", "Жокко чыгарылды"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="job_images/",
                        verbose_name="Сүрөт",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Көрүүлөр"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Түзүлгөн убакыт"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Жаңыртылган убакыт"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Жарыялаган",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жумуш",
                "verbose_name_plural": "Жумуштар",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Билдирүү")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Өтүнгөн убакыт"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Өтүнүүчү",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                        verbose_name="Жумуш",
                    ),
                ),
            ],
            options={
                "verbose_name": "Өтүнмө",
                "verbose_name_plural": "Өтүнмөлөр",
                "ordering": ["-created_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
